name: Feature request
description: Something the bar should do or show
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What should the bar do?
    validations:
      required: true
